[package]
name = "gtklayershelltest"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
gtk4-layer-shell = "0.5.0"
# GIO (GLib I/O) for Application and signal traits
gio = "0.20"
# GTK4 aliased as `gtk` so we can use `use gtk::prelude::*;`
gtk = { package = "gtk4", version = "0.9" }
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
hyprland = { git = "https://github.com/sergioahp/hyprland-rs", branch = "fix-active-window-ready-state" }
futures-util = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0"
thiserror = "1.0"
zbus = "5.7.1"
zbus_names = "4.2.0"
zvariant = "5.5.3"
futures = "0.3.31"
